### PR TITLE
subscrier to subscriber

### PR DESCRIPTION
**Pull request by brntbeer**
Related to https://github.com/knadh/listmonk/issues/28 and my general (albeit small for now) interest in the Listmonk project, i wanted to help out. I was adding some new documentation for the API and noticed the typo! 😄 

looking forward to helping more!

### CODE REVIEW

**Comment by brntbeer** [comment]
@knadh 👋 just wondering if you had the chance to review this yet! let me know if there's anything i can do to help

**Comment by brntbeer** [comment]
@Quadrisheriff i noticed in #4 you added some documentation that's actually way better than mine 😍 i'm going to close this in favor of yours

**Comment by knadh** [comment]
@brntbeer my apologies. I somehow had completely missed this PR!

**Comment by brntbeer** [comment]
@knadh not a problem! as mentioned, #4 is way better and i'm jealous of the work being done there =)

**Pull request closed without merging**
